[package]
name = "kruskal"
version = "0.1.0"
authors = ["rafael_ignaulin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-graph = "0.19.2"